<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>Aquarium.Emulator</RootNamespace>
    <AssemblyName>Aquarium.Emulator</AssemblyName>
    <ApplicationTitle>Aquarium Emulator</ApplicationTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Aquarium.Models\Aquarium.Models.csproj" />
    <ProjectReference Include="..\..\shared\Aquarium.Protocol\Aquarium.Protocol.csproj" />
    <ProjectReference Include="..\..\shared\Aquarium.EmulatorCore\Aquarium.EmulatorCore.csproj" />
  </ItemGroup>
</Project>
