; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:seeed_xiao_esp32s3]
;platform = espressif32
;board = seeed_xiao_esp32s3
;framework = arduino


[env:esp32-s3-devkitc-1]
monitor_speed = 115200
monitor_encoding = UTF-8
platform = espressif32
board = esp32s3_zero_4mb
framework = arduino

board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  olikraus/U8g2 @ ^2.36.0
  adafruit/RTClib @ ^2.1.4
  madhephaestus/ESP32Servo @ ^3.1.3
  milesburton/DallasTemperature @ ^4.0.6
  paulstoffregen/OneWire @ ^2.3.8
  bblanchon/ArduinoJson @ ^6.21.4
