<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Aquarium.EmulatorCore</AssemblyName>
    <RootNamespace>Aquarium.EmulatorCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aquarium.Models\Aquarium.Models.csproj" />
    <ProjectReference Include="..\Aquarium.Protocol\Aquarium.Protocol.csproj" />
  </ItemGroup>
</Project>
